# Generated by Django 6.0.1 on 2026-01-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('zaid', 'Zaid')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('optimal_ph_min', models.DecimalField(decimal_places=2, default=6.0, max_digits=4)),
                ('optimal_ph_max', models.DecimalField(decimal_places=2, default=7.5, max_digits=4)),
                ('nitrogen_requirement', models.DecimalField(decimal_places=2, help_text='N in kg/acre', max_digits=5)),
                ('phosphorus_requirement', models.DecimalField(decimal_places=2, help_text='P in kg/acre', max_digits=5)),
                ('potassium_requirement', models.DecimalField(decimal_places=2, help_text='K in kg/acre', max_digits=5)),
            ],
        ),
    ]
