# Generated by Django 6.0.1 on 2026-01-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crops/'),
        ),
        migrations.AddField(
            model_name='crop',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
