# Generated by Django 6.0.1 on 2026-01-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_image_crop_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
