# Generated by Django 6.0.1 on 2026-01-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_farm_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('farmer', 'Farmer'), ('agronomist', 'Agronomist')], default='farmer', max_length=20),
        ),
    ]
