# Generated by Django 4.2.29 on 2026-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('seed', 'Seed'), ('crop', 'Crop'), ('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('equipment', 'Equipment'), ('fuel', 'Fuel')], max_length=20),
        ),
    ]
