# Generated by Django 6.0.1 on 2026-01-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_alter_farmerprofile_farm_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='soil_type',
            field=models.CharField(choices=[('Alluvial', 'Alluvial Soil'), ('Black', 'Black Soil (Regur)'), ('Red', 'Red Soil'), ('Laterite', 'Laterite Soil'), ('Desert', 'Desert / Arid Soil'), ('Forest', 'Forest / Mountain Soil'), ('Saline', 'Saline / Alkaline Soil'), ('Peaty', 'Peaty / Marshy Soil'), ('Loamy', 'Loamy Soil'), ('Clay', 'Clay Soil'), ('Sandy', 'Sandy Soil')], max_length=50),
        ),
    ]
