# Generated by Django 6.0.1 on 2026-01-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_alter_land_soil_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('portal', 'Government Agriculture Portal'), ('helpline', 'Helpline & Emergency'), ('email', 'Official Contact Email'), ('insurance', 'Insurance & Subsidy'), ('advisory', 'Weather & Advisory')], max_length=50)),
                ('description', models.CharField(help_text='One line description', max_length=255)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('helpline_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
