# Generated by Django 6.0.1 on 2026-01-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_governmentresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentresource',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
