# Generated by Django 6.0.1 on 2026-01-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_governmentresource_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='land',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
