# Generated by Django 6.0.1 on 2026-01-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recommended', models.DateField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.land')),
                ('recommended_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recommended', models.DateField(auto_now_add=True)),
                ('nitrogen_recommended', models.DecimalField(decimal_places=2, max_digits=5)),
                ('phosphorus_recommended', models.DecimalField(decimal_places=2, max_digits=5)),
                ('potassium_recommended', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.land')),
            ],
        ),
    ]
