# Generated by Django 6.0.1 on 2026-01-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tested', models.DateField()),
                ('ph_level', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nitrogen', models.DecimalField(decimal_places=2, help_text='N in ppm', max_digits=5)),
                ('phosphorus', models.DecimalField(decimal_places=2, help_text='P in ppm', max_digits=5)),
                ('potassium', models.DecimalField(decimal_places=2, help_text='K in ppm', max_digits=5)),
                ('moisture', models.DecimalField(decimal_places=2, help_text='Moisture %', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_data', to='farmers.land')),
            ],
            options={
                'ordering': ['-date_tested'],
            },
        ),
    ]
