# Generated by Django 6.0.1 on 2026-01-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='organic_carbon',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Organic Carbon %', max_digits=5, null=True),
        ),
    ]
