# Generated by Django 6.0.1 on 2026-01-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0003_alter_soildata_organic_carbon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soildata',
            name='organic_carbon',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Organic Carbon %', max_digits=5, null=True),
        ),
    ]
