# Generated by Django 6.0.1 on 2026-01-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0004_alter_soildata_organic_carbon'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
